# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM mark86092/jupyter-notebook:scipy

MAINTAINER Jupyter Project <jupyter@googlegroups.com>

# Install PyTorch
RUN pip --no-cache-dir install http://download.pytorch.org/whl/cu80/torch-0.2.0.post2-cp36-cp36m-manylinux1_x86_64.whl torchvision
